language: node_js
nodejs:
  - 8

script:
  - npm run ci

notifications:
  email:
    recipients:
      - secure: "jDwf0hUN3mxdrcXljXAu/mRm3dFv09ynVMMkAr7XcWL0/O4Y1EuVR3x+0diOw/MDUaspyEd/eBgRGZuSBARJUIw6ams8rWaWrouqlDpih8YGxh+0mdATa5PUY3rvRIHIKz17pkrOH5ZZKwwQv9nAeMylBJwooMS5vro8Z5aJpe15bs/RXl8wX61efv2pJcP3iNYJEAUYt9z1m09FyjXtzrVqBMJntoQ2y4azEPQplIPjyqaF8xNqozvuj/nJsFXp6x2VjARrHHlTQwQDDeYrQooP0tyeCV4RrZs3c7OCRWAz8xTY9TBscR5ca7CchwhodwGaU/7KrQ1s4h7ryfrvbClLOBlFe7tzKeNi8vHajftQcET/azDnmYK1ugaglgah2jIr9l8oaXSIqvm6t7yxweNa3UgzK/DIX4+3ozCR9VyO2o/1TTxqTt4R7ul9CvPOwPignjTqg5c1rom5Q6W/xrEoXh6UZV8/cXhinvoctvDUGayPTvubtwjUKwEPQdUbfj8dVfrlYa0M41XFtAw1NZUIbXkOdrifQJw+HxtjBihuQ1dOCiUzGFHvl6BXNUgO8MUX9vJFalJ27uP7fHaCEqLmYqqKeNLx11rXJ6JX33C4XKNM+WVdTZGvJYErJAKV9g0FBcbl0n5VZyMhP5k6EiQkIbl6uTAM8WpbziFxP7w="
