#!/bin/bash
# Expects as the only argument a path to an existing empty folder.
set -o errexit
set -o nounset
set -o pipefail

if [[ ("$#" -ne 1) || (! -d "$1") || "$(ls -I lost+found -A $1)" ]]; then
  echo "Error: The only argument must be an existing empty folder."
  exit 1
fi

echo "Backing up files..."
tar --create --verify --file=$1/files.tar.gz --directory=/home/a Documents Pictures Videos
echo "Verifying files..."
tar --compare --file=$1/files.tar.gz --directory=/home/a

echo "Backup completed successfully."
