#!/bin/bash
# Expects as the only argument a path to an existing empty folder.
set -o errexit
set -o nounset
set -o pipefail

echo "Backing up files..."
tar --create --file=$1/files.tar.gz --directory=/home/a Documents Pictures Videos
echo "Verifying files..."
tar --compare --file=$1/files.tar.gz --directory=/home/a

echo "Backup completed successfully."
