#!/bin/bash
# Formats the only connected SanDisk USB stick as a LUKS encrypted ext4 volume
set -o errexit
set -o nounset
set -o pipefail

device=( $(readlink -e /dev/disk/by-id/*SanDisk*:0) ) || device=()

if [ ${#device[@]} -ne 1 ]; then
  echo "Make sure exactly one SanDisk USB stick is plugged in."
  exit 1
fi

mounts=( $(lsblk -l -n -o MOUNTPOINT $device) )
lukss=( $(lsblk -l -n -o NAME $device | tail -n +2) )

if [[ (${#mounts[@]} -ne 0) || (${#lukss[@]} -ne 0) ]]; then
  echo "Error: The device is still mounted and/or LUKS still unlocked."
  exit 1
fi

read -p "Volume Name: " volumeName

sudo wipefs -f -a $device
sudo cryptsetup luksFormat --type luks2 $device
sudo cryptsetup luksOpen $device $volumeName
sudo mkfs.ext4 -L $volumeName -E root_owner=$UID:$(id -g) /dev/mapper/$volumeName
sleep 1
sudo cryptsetup luksClose $volumeName
sleep 1
udisksctl power-off -b $device
echo "Done, you can now unplug the USB stick."
